# Generated by Django 5.1.7 on 2025-05-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=64)),
                ('epos', models.CharField(choices=[('C', 'Cashier'), ('I', 'Inventory')], default='I', max_length=16)),
                ('epass', models.CharField(max_length=32)),
            ],
        ),
    ]
