# Generated by Django 5.1.7 on 2025-05-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='epos',
            field=models.CharField(choices=[('Cshr', 'Cashier'), ('Invt', 'Inventory')], default='Invt', max_length=16),
        ),
    ]
