# Generated by Django 5.1.7 on 2025-05-02 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
