# Generated by Django 5.2 on 2025-05-03 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0010_remove_sale_eid_delete_order_delete_sale'),
        ('inventory', '0011_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
