# Generated by Django 5.1.7 on 2025-05-02 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
