# Generated by Django 5.1.7 on 2025-05-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='samount_change',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='samount_payed',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sgrand_total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='ssub_total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='stax_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='stax_percentage',
            field=models.FloatField(default=0),
        ),
    ]
