# Generated by Django 5.1.7 on 2025-05-02 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0004_alter_sale_samount_change_alter_sale_samount_payed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='sprice',
        ),
    ]
