# Generated by Django 5.1.7 on 2025-05-02 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0005_remove_sale_sprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
