# Generated by Django 5.1.7 on 2025-05-02 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0006_delete_order'),
        ('inventory', '0011_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odate', models.DateField(auto_now_add=True)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashier.sale')),
            ],
        ),
    ]
