# Generated by Django 5.2 on 2025-05-03 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0007_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
