# Generated by Django 5.2 on 2025-05-03 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0009_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='eid',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
