# Generated by Django 5.2 on 2025-05-03 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashier', '0010_remove_sale_eid_delete_order_delete_sale'),
        ('inventory', '0013_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdate', models.DateTimeField(auto_now_add=True)),
                ('stotal', models.FloatField(default=0)),
                ('spayed', models.FloatField(default=0)),
                ('schange', models.FloatField(default=0)),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashier.sale')),
            ],
        ),
    ]
