# Generated by Django 5.2 on 2025-05-07 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0011_initial'),
        ('inventory', '0013_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='exid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.extra'),
        ),
    ]
