# Generated by Django 5.2 on 2025-05-07 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0012_order_exid'),
        ('inventory', '0013_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='exid',
        ),
        migrations.CreateModel(
            name='SaleExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.extra')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashier.sale')),
            ],
        ),
    ]
