# Generated by Django 5.2 on 2025-05-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0013_remove_order_exid_saleextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
